name: GNU/Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: update
      run: 
        sudo apt-get update
    - name: install sdl2
      run:
        sudo apt-get install libsdl2-dev
    - name: install sdl2 mixer
      run:
        sudo apt-get install libsdl2-mixer-dev
    - name: make
      run: make
